services:
  php:
    build: ./
    container_name: hm-nutrition-php
    volumes:
      - ./:/var/www/html
    networks:
      - healthyMe

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/healthyMe
    container_name: hm-nutrition-nginx
    restart: always
    networks:
      - healthyMe
    ports:
      - "10040:80"

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: hm-mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

volumes:
  mysql:

networks:
  healthyMe: